### PR TITLE
Partner organizations

### PR DESCRIPTION
**Pull request by htysc**
Add three fields:
- Is partner organization? (boolean)
- Endpoint URL (for connecting to the partner org)
- Endpoint port (for connecting to the partner org)

### CODE REVIEW

**Review by LesterLyu — APPROVED** [review]

**Comment by LesterLyu** [comment]
Please add a new field `apiKey`(string) which will be used to access the partner SNM-I deployment.

**Comment by htysc** [comment]
I noticed the 'dcat' namespace has an 'endpointURL' property. Should that be used for the internalKey of 'endpointUrl' in GDBOrganizationModel? But is there a property for 'endpointPort'?

**Comment by htysc** [comment]
It looks like the BooleanRadioField isn't storing False values.

**Comment by htysc** [comment]
Actually, never mind about the boolean issues in the backend.

**Pull request merged**
